<scene>        ::= scene <identifier><newline><scenebody><newline>end scene
<scenebody>    ::= <newline>|<builtin><newline><scenebody>

<action>       ::= action <identifier><newline><actionbody><newline>end action|
					action <identifier><values><newline><actionbody><newline>end action
<values>	   ::= <literal> <values>|<literal>

<actionbody>   ::= <newline>|<output><newline><actionbody>
<output>	   ::= output(<collapse>|<identifier>|<place>):
<collapse>	   ::= collapse(<colbody>)
<colbody>	   ::= <identifier>, <colbady>|<identifier>|<empty> 

<scenebody>    ::= <newline>|<builtin><newline><scenebody>

<identifier>   ::= <identchar>|<identchar><identifier>
<blockId>	   ::= <blockcall>.<blockId>|<identifier>
<builtin>      ::= <listen>|<set>

<listen>       ::= listen <keymap> <andClause> <identifier>|listen <keymap> <andClause> <blockId>
<keymap>       ::= KEY_DOWN_ARROW|KEY_UP_ARROW|KEY_RIGHT_ARROW|KEY_LEFT_ARROW|KEY_ENTER|KEY_LEFT_SHIFT
<andClause>	   ::= <empty>|and <identifier> <andClause>

<set>          ::= set <identifier> <literal>|setBackGround <indentifier>|setFloorlevel 

<literal>      ::= <qstring>|<int>

<qstring>      ::= "<string>"|'<string>'
<string>       ::= <alphachar>|<alphachar><string>
<alphachar>    ::= a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z
<identchar>    ::= a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|_

<unsigned-int> ::= 0|1|2|3|4|5|6|7|8|9
<int>          ::= <unsigned-int>|-<unsigned-int>|+<unsigned-int>

<setValue>	   ::= <variable> <int>

<asClause>	   ::= as <identifier>

<variables>	   ::= <identifier>, <variables>|<identifier>[], <variables>|<empty>

<load>		   ::= loadSprite <qstring> <asClause>|
					loadGif <qstring> <asClause>|
					loadSound <qstring> <asClause>|
					loadVideo <qstring> <asClause>|
					loadBackground <qstring> <asClause>
					
<export>	   ::= export <identifier>

<block>		   ::= block <identifier>[<variables>] <stmts> end block
<stmts>		   ::= <block><stmts>|<action><stmts>|<event><stmts>|<inherit><stmts>|<set><stmts>|<onClause><stmts>|<newline>
<inherit>	   ::= inherit <blockcall><newline><inherit>| inherit <blockcall><newline>
<blockcall>	   ::= <identifier>[]

<run>		   ::= run <event>

<if-cond>	   ::= if(<exp>)<stmts> end if
<collide>	   ::= <action> collide <action>
<onClause>	   ::= <action> on <action>
<exp>		   ::= <identifier><compare><identifier>|
					<identifier><compare><literal>|
					<literal><compare> <indentifier>|
					<literal><compare><literal>

<place>		   ::= place(<identifier>, <int>, <int>)
<move>		   ::= move(<identifier>, <int>, <int>)

<compare>	   ::= == | < | > | != | <= | >=
